// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU9I4P2ywG2VQWvXokzO6O4nG9vUsoGsk',
    appId: '1:425626089858:web:19ca17d64729e7b340b79b',
    messagingSenderId: '425626089858',
    projectId: 'mindcare-3a420',
    authDomain: 'mindcare-3a420.firebaseapp.com',
    storageBucket: 'mindcare-3a420.firebasestorage.app',
    measurementId: 'G-5TST0276PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCamWHUjzKc9JU3jSt_IGzijShpQlsL2B4',
    appId: '1:425626089858:android:8cea3b8c4b2cdcb840b79b',
    messagingSenderId: '425626089858',
    projectId: 'mindcare-3a420',
    storageBucket: 'mindcare-3a420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGW0ZR3sXDiPppKafgUnumz-AMmygzIWE',
    appId: '1:425626089858:ios:40c07fe4c6eb2e9f40b79b',
    messagingSenderId: '425626089858',
    projectId: 'mindcare-3a420',
    storageBucket: 'mindcare-3a420.firebasestorage.app',
    iosBundleId: 'com.example.wellcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU9I4P2ywG2VQWvXokzO6O4nG9vUsoGsk',
    appId: '1:425626089858:web:c6fa83acfde9c50040b79b',
    messagingSenderId: '425626089858',
    projectId: 'mindcare-3a420',
    authDomain: 'mindcare-3a420.firebaseapp.com',
    storageBucket: 'mindcare-3a420.firebasestorage.app',
    measurementId: 'G-8R36VFSHJ1',
  );
}
